version: '3.8'

services:
  # Redis for BullMQ queues
  redis:
    image: redis:7-alpine
    container_name: fides-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder  # Use builder stage for dev
    container_name: fides-backend-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
      - JWT_SECRET=dev-jwt-secret
      - JWT_EXPIRATION=7d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:3000
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=5242880
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend-dev-uploads:/app/uploads
    depends_on:
      - redis
    command: npm run start:dev

  # Frontend Next.js (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder  # Use builder stage for dev
    container_name: fides-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  redis-dev-data:
  backend-dev-uploads:

networks:
  default:
    name: fides-dev-network