[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm run start:prod"
buildCommand = "cd backend && npm install && npm run build"
watchPatterns = ["backend/**"]

[[services]]
name = "fides-backend"