[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.railway"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "fides-backend"